type Author {
  name: String!
  books: [Book!] @relation
}

type Book {
  author: Author!
  title: String!
  image: String!
  description: String!
  bookshopLink: String!
}

type Query {
  authors: [Author!]
}
