type Author {
  name: String!
  books: [Book!] @relation
}

type Book {
  author: Author!
  title: String!
  image: String!
  description: String!
  bookshopLink: String!
}

type BlogBlockA {
  foo: String
}

type BlogBlockB {
  bar: String
}

union BlogBlocks = BlogBlockA | BlogBlockB

type Query {
  authors: [Author!]
  blogExperience: [BlogBlocks!]
}
